# Generated by Django 2.2.5 on 2022-02-21 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_follow',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='f_uid',
            field=models.ManyToManyField(through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
